# API versi 1
apiVersion: v1

# object = Secret
kind: Secret

# metadata
metadata:SS
  # nama 
  name: mongo-secret

# environtment
data:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
